"""Golden-file regression against the source's ACTUAL ``RealMotionReference``.

``tests/golden/golden_reference.npz`` is generated by running the source
(``B/models/evaluation/motion_reference.py``'s ``RealMotionReference.build``
+ ``.invariance_score``) against 12 real rollouts and 5 synthetic test cases
-- see ``tests/golden/MANIFEST.json`` for provenance (source sha256, seeds).
This subpackage does not generate it; when the file is absent every test here
is skipped rather than failing.

Fixture layout (flat ``.npz``, ``__`` as a path separator):

* ``reference__inv_baseline__<key>``, ``reference__quantiles__<key>``,
  ``reference__feat_mu``, ``reference__feat_cov``, ``reference__quantity_keys``
  -- the fitted reference (10 invariant keys, 6 quantity keys).
* ``case{1..5}_<name>__pis``, ``__n_terms``, ``__scores__<key>``,
  ``__residuals__<key>``, ``__w1__w1_<key>``, ``__kfd_eligible`` -- the
  source's own ``invariance_score``/``w1`` output for 5 residual dicts,
  including one (``case2_missing_q``) that omits the 3 joint-angle-only
  residual keys entirely -- the exact scenario defect D3 describes.
* ``kfd``, ``kfd_n_cases`` -- aggregate KFD over the ``kfd_eligible`` cases.

No raw per-frame samples are exported (only aggregated results), so W1/KFD
cannot be independently recomputed from this fixture -- those are covered by
synthetic tests in ``tests/test_kfd.py`` instead. What this fixture uniquely
gives us is a real ``inv_baseline`` and 5 real residual dicts, which is enough
to check both required things: (1) ``legacy=True`` reproduces the source's
PIS/scores/``n_terms`` exactly, including its 7-vs-10 term-count asymmetry on
``case2_missing_q``; (2) the fixed path's *only* observable difference on the
well-conditioned cases is the numerical no-op (D3b), while on
``case2_missing_q`` it differs exactly as documented (D3): ``n_terms`` becomes
the fixed 10 under ``policy="strict"``/``"available"`` instead of legacy's
accidental 7, and ``policy="strict"`` reports ``NaN`` rather than silently
averaging over fewer terms.
"""
from __future__ import annotations

import math
import re

import numpy as np
import pytest

from kinescore.reference.fingerprint import UNIT_FLOORS, RealMotionReference
from kinescore.reference.normalize import invariance_score

GOLDEN_DIR = __import__("pathlib").Path(__file__).parent / "golden"
GOLDEN_PATH = GOLDEN_DIR / "golden_reference.npz"

pytestmark = pytest.mark.skipif(
    not GOLDEN_PATH.exists(),
    reason=f"golden fixture not present at {GOLDEN_PATH}")


def _prefixed(d, prefix):
    return {k[len(prefix):]: v for k, v in d.items() if k.startswith(prefix)}


@pytest.fixture(scope="module")
def golden():
    with np.load(GOLDEN_PATH, allow_pickle=True) as d:
        yield {k: d[k] for k in d.files}


@pytest.fixture(scope="module")
def reference(golden):
    """Reconstruct a RealMotionReference from the fitted golden fields.

    ``floors`` has no legacy counterpart (defect D3b is new), so it is filled
    from ``UNIT_FLOORS`` only -- no median-absolute-deviation component,
    since the raw per-rollout residuals used to fit the real reference are
    not part of this fixture. That is a strictly *more conservative* (i.e.
    smaller-or-equal) floor than ``RealMotionReference.build`` would produce,
    which only strengthens the no-op assertions below.
    """
    inv_baseline = {k: float(v) for k, v in _prefixed(golden, "reference__inv_baseline__").items()}
    floors = {k: UNIT_FLOORS.get(k, 0.0) for k in inv_baseline}
    quantiles = _prefixed(golden, "reference__quantiles__")
    return RealMotionReference(
        dt=0.1, suite_id="golden:reference", term_keys=tuple(sorted(inv_baseline)),
        inv_baseline=inv_baseline, floors=floors, quantiles=quantiles,
        feat_mu=golden["reference__feat_mu"], feat_cov=golden["reference__feat_cov"],
        quantity_keys=tuple(golden["reference__quantity_keys"].tolist()), n_q=100)


def _case_names(golden):
    return sorted({m.group(1) for k in golden if (m := re.match(r"(case\d+_\w+?)__pis", k))})


def test_golden_fixture_has_the_expected_cases(golden):
    names = _case_names(golden)
    assert names == [
        "case1_near_zero_baseline", "case2_missing_q", "case3_severe_teleport",
        "case4_high_freq_jitter", "case5_moderate_mixed",
    ]


@pytest.mark.parametrize("case", [
    "case1_near_zero_baseline", "case2_missing_q", "case3_severe_teleport",
    "case4_high_freq_jitter", "case5_moderate_mixed",
])
def test_legacy_replica_reproduces_source_pis_scores_and_n_terms(golden, reference, case):
    residuals = {k: float(v) for k, v in _prefixed(golden, f"{case}__residuals__").items()}
    expected_pis = float(golden[f"{case}__pis"])
    expected_n = int(golden[f"{case}__n_terms"])
    expected_scores = {k: float(v) for k, v in _prefixed(golden, f"{case}__scores__").items()}

    result = invariance_score(residuals, reference, legacy=True)

    assert result.pis == pytest.approx(expected_pis, rel=1e-5, abs=1e-9)
    assert result.n_terms == expected_n
    assert set(result.per_key) == set(expected_scores)
    for k, exp in expected_scores.items():
        assert result.per_key[k] == pytest.approx(exp, rel=1e-5, abs=1e-9)


def test_case2_missing_q_reproduces_the_documented_7_vs_10_asymmetry(golden, reference):
    """The exact motivating scenario for D3: a clip scored without joint
    angles loses 3 residual keys (limit/vel violation fractions, effort
    proxy), so the legacy mean is over 7 terms while the full set is 10 --
    and legacy reports both as directly comparable PIS numbers."""
    residuals_missing = {k: float(v) for k, v in
                         _prefixed(golden, "case2_missing_q__residuals__").items()}
    residuals_full = {k: float(v) for k, v in
                      _prefixed(golden, "case1_near_zero_baseline__residuals__").items()}

    legacy_missing = invariance_score(residuals_missing, reference, legacy=True)
    legacy_full = invariance_score(residuals_full, reference, legacy=True)
    assert legacy_missing.n_terms == 7
    assert legacy_full.n_terms == 10
    assert legacy_missing.n_terms != legacy_full.n_terms  # the bug, reproduced

    fixed_missing = invariance_score(residuals_missing, reference, policy="strict")
    fixed_full = invariance_score(residuals_full, reference, policy="strict")
    # The fix: both report the SAME n_terms (the suite's fixed declared set).
    assert fixed_missing.n_terms == fixed_full.n_terms == 10 == fixed_missing.n_terms_declared
    assert math.isnan(fixed_missing.pis)          # incomplete -> NaN, not a smaller mean
    assert math.isfinite(fixed_full.pis)

    avail_missing = invariance_score(residuals_missing, reference, policy="available")
    # policy="available" recovers legacy's accidental count, but now it is
    # RECORDED against the declared total rather than presented as final.
    assert avail_missing.n_terms == 7
    assert avail_missing.n_terms_declared == 10
    assert avail_missing.pis == pytest.approx(legacy_missing.pis, rel=1e-5, abs=1e-9)


@pytest.mark.parametrize("case", [
    "case1_near_zero_baseline", "case3_severe_teleport",
    "case4_high_freq_jitter", "case5_moderate_mixed",
])
def test_fixed_path_is_a_numerical_no_op_on_well_conditioned_real_cases(golden, reference, case):
    """These 4 cases carry all 10 residual keys, and every non-`_frac` key's
    real baseline is comfortably above its floor (see fixture values in
    ``reference__inv_baseline__*``) -- exactly the "well-conditioned" regime
    D3b's no-op guarantee is about. The fixed PIS must match the legacy one
    to a tiny, epsilon-scale gap, not merely "in the same ballpark"."""
    residuals = {k: float(v) for k, v in _prefixed(golden, f"{case}__residuals__").items()}
    legacy = invariance_score(residuals, reference, legacy=True)
    fixed = invariance_score(residuals, reference, policy="strict")
    assert fixed.n_terms == fixed.n_terms_declared == 10
    assert math.isfinite(fixed.pis)
    assert math.isclose(fixed.pis, legacy.pis, rel_tol=0.0, abs_tol=1e-6)
